DROP DATABASE IF EXISTS db_projetfa;
CREATE DATABASE IF NOT EXISTS db_projetfa  CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP USER IF EXISTS 'Cli_Read'@'%';
CREATE USER 'Cli_Read'@'%' IDENTIFIED BY 'pwdPourCli_R';